Style/AlignHash:
  Enabled: false

Metrics/AbcSize:
  Max: 30
Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 20

Metrics/LineLength:
  Max: 100

Metrics/PerceivedComplexity:
  Max: 10

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'install/*'